apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nodemedic
resources:
  - namespace.yaml
  - crds/noderemediations.nodemedic.io-v1.yml
  - crds/remediationpolicies.nodemedic.io-v1.yml
  - rbac.yaml
  - deployment.yaml
